boxes/urls.py
from django.urls import path
from .views import *
from .api_views import *

urlpatterns = [
    path('region/form', region_form, name='region_form'),
    path('region/index', region_index, name='region_index'), # type: ignore
    path('region/update/<str:pk>', region_update, name='region_update'),
    # path('image_upload', hotel_image_view, name='image_upload'),
    path('boxeslist', boxeslist, name='boxeslist'),
    path('boxesstatus/<str:status>', boxesstatus, name='boxesstatus'),
    path('boxesselected', box_selected_send, name='boxesselected'),
    path('boxselect/<str:pk>', box_select, name='boxselect'),
    path('success', success, name='success'),
    path('cratebox', create_box, name='createbox'),
    path('boxview/<str:pk>', box_view, name='boxview'),
    path('boxupdate/<str:pk>', box_update, name='boxupdate'),
    path('boxfromto/<str:pk>', box_fromto, name='boxfromto'),
    # notification ursl notification_update
    path('notification/index', notification_index, name="notification"),
    path('notification/form', notification_form, name="notification_form"),
    path('notification/update/<str:pk>', notification_update, name='notification_update'),
    # path('notification/view/<str:pk>', notification_view, name='notification_view'),
    # feedbac urls
    path('feedback/index', feedback_index, name="feedback"),
    path('feedback/form', feedback_form, name="feedback_form"),
    path('feedback/answer/<str:pk>', feedback_answer, name="feedback_answer"),
    # urls for API
    path('boxes', BoxesAPIList.as_view(), name='boxesapi'),
    path('boxes/<str:pk>', BoxesAPIList.as_view(), name='boxesapiupdate'),
    path('boxreject/<str:pk>', BoxReject.as_view(), name='BoxReject'),
    path('regions', RegionAPIList.as_view(), name='regionsapi'),
    # path('regioncreate', RegionCreate.as_view(), name='regioncreate'),
    path('regionshi', RegionHi.as_view(), name='regionshiapi'),
    path('regionscity', RegionCity.as_view(), name='regionscityapi'),
    # path('regionscity/<str:region_hi>', RegionCity.as_view(), name='regionscityhiapi'),    
    path('boxhistory/<str:pk>', BoxHistoryAPIList.as_view(), name='boxhistoryapi'),
    # feedback API urls
    path('feedback', FeedbackAPIList.as_view(), name='feedbackapi'),
    path('feedback/<int:pk>', FeedbackAPIList.as_view(), name='feedbackapi'),
    # notification API urls
    path('notification', NotificationList.as_view(), name='notificationapi'),
    path('notification/<int:pk>', NotificationList.as_view(), name='notificationapi'),
]

yoldatm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
from .views import dashboard


urlpatterns = [
    path('yolloadmin/admin/', admin.site.urls),
    path('yolloadmin/', dashboard, name='dashboard'),
    #path('users/', include('users.urls')),
    #path('', include('boxes.urls')),
    path('yolloadmin/api/box/', include('boxes.urls')),
    path('yolloadmin/api/user/', include('users.urls')),
    path('yolloadmin/api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('yolloadmin/api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('yolloadmin/api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

boxes/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid, decimal


class Region(models.Model):
    region_type = (
        ('AG', 'Aşgabat'),
        ('AH', 'Ahal'),
        ('BN', 'Balkan'),
        ('MR', 'Mary'),
        ('LB', 'Lebap'),
        ('DZ', 'Daşoguz'),
    )
    name = models.CharField(max_length=50)
    tarif = models.DecimalField(max_digits=20, decimal_places=2, default=decimal.Decimal(0.0))
    hi_region = models.CharField(max_length=50, default='0', blank=True)
    # type_region = models.CharField(max_length=10, choices=region_type, 
        # verbose_name="Region district")ll

    def __str__(self) -> str:
        return self.name


def set_image_name(instance, filename):
    if filename == "":
        return "images/emptybox.png"

    ext = filename.split('.')[-1]
    return "images/{0}.{1}".format(uuid.uuid4(), ext)


class Boxes(models.Model):
    val = (
        ('TMT', 'Manat'),
        ('USD', 'Dollar')
    )
    toleg = (
        ('tolendi', 'tolendi'),
        ('tolenmedi', 'tolenmedi'),
    )
    inputdate = models.DateTimeField(auto_now_add=True)
    updatedate = models.DateTimeField(auto_now=True)
    clientfrom = models.CharField(max_length=255, blank=True)
    clientto = models.CharField(max_length=255, blank=True)
    phonefrom = models.CharField(max_length=25)
    phoneto = models.CharField(max_length=25, default="", blank=True)
    addressfrom = models.CharField(max_length=255, default="", blank=True)
    addressto = models.CharField(max_length=255, default="", blank=True)
    tarif = models.DecimalField(max_digits=20, decimal_places=2, default=decimal.Decimal(0.0)) 
    amount = models.DecimalField(max_digits=20, decimal_places=2, default=decimal.Decimal(0.0)) 
    weight = models.DecimalField(max_digits=20, decimal_places=3, default=decimal.Decimal(0.0)) 

    volumesm = models.DecimalField(max_digits=20, decimal_places=3, default=decimal.Decimal(0.0)) 
    delivery = models.DecimalField(max_digits=20, decimal_places=2, default=decimal.Decimal(0.0)) 
    minsm = models.DecimalField(max_digits=20, decimal_places=2, default=decimal.Decimal(0.0)) 
    maxsm = models.DecimalField(max_digits=20, decimal_places=2, default=decimal.Decimal(0.0)) 

    placecount = models.IntegerField(default=0)
    discount = models.DecimalField(max_digits=20, decimal_places=2, default=decimal.Decimal(0.0)) 
    valuta = models.CharField(max_length=25, choices=val, default="tmt")
    status = models.CharField(max_length=25, default="create")
    comment = models.CharField(max_length=2500, null=True, blank=True)
    select = models.BooleanField(default=False)
    payment = models.CharField(max_length=25, choices=toleg, null=True, blank=True)
    boximg = models.ImageField(
        upload_to=set_image_name, default="images/emptybox.png", blank=True)
    regionfrom = models.ForeignKey('Region', related_name="A_region", on_delete=models.PROTECT, null=True)
    regionto = models.ForeignKey(
        'Region', related_name="B_region", on_delete=models.PROTECT, null=True, blank=True)
    user = models.ForeignKey(User, verbose_name='Users',
                             on_delete=models.SET_NULL, blank=True, default=1, null=True) # type: ignore

    def __str__(self) -> str:
        return self.phonefrom


class BoxHistory(models.Model):
    stats = (
        ('create', 'Create'),
        ('called', 'Called'),
        ('approved', 'Approved'),
        ('accepted', 'Accepted'),
        ('sent', 'Sent'),
        ('rejected', 'Rejected'),
        ('canceled', 'Canceled'),
        ('closed', 'Closed')
    )
    box = models.ForeignKey('Boxes', verbose_name='Boxes', on_delete=models.CASCADE)
    inputdate = models.DateTimeField(auto_now=True)
    userfrom = models.ForeignKey(User, related_name="UserFrom", on_delete=models.SET_NULL, blank=True, default=1, null=True) # type: ignore
    userto = models.ForeignKey(User, related_name="UserTo", on_delete=models.SET_NULL, blank=True, default=1, null=True) # type: ignore
    regionbh = models.ForeignKey(Region, related_name="H_region", verbose_name="RegionBH", on_delete=models.PROTECT,default=0) # type: ignore
    status = models.CharField(max_length=25, choices=stats, default="create")

    def __str__(self) -> str:
        return self.status + " - " + str(self.inputdate)
    

class Cart(models.Model):
    inputdate = models.DateTimeField(auto_now_add=True)
    box = models.ForeignKey('Boxes', verbose_name='Boxes', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name="UserCart", on_delete=models.SET_NULL, blank=True, default=1, null=True) # type: ignore
    status = models.IntegerField(default=0)
    comment = models.CharField(max_length=50, blank=True)


class Notification(models.Model):
    inputdate = models.DateTimeField(auto_now_add=True)
    theme = models.CharField(max_length=150)
    maintxt = models.TextField(max_length=2500, default='')
    published = models.BooleanField(default=False)
    image = models.ImageField(
        upload_to=set_image_name, default="images/emptybox.png", blank=True)


class Feedback(models.Model):
    inputdate = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, related_name="UserFeedback", on_delete=models.SET_NULL, null=True)
    ansuser = models.ForeignKey(User, related_name="AnswerUserFeedback", on_delete=models.SET_NULL, blank=True, null=True)
    comment = models.TextField(max_length=2500, default="")
    answer = models.TextField(max_length=2500, default="", blank=True)
    answerdate = models.DateTimeField(blank=True, null=True)

    def __str__(self) -> str:
        return self.comment + " - " + str(self.inputdate)


class Point(models.Model):
    inputdate = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, related_name="UserPoint", on_delete=models.SET_NULL, null=True)
    amount = models.IntegerField(default=1)
    type = models.IntegerField(default=0)

boxes/forms.py
from typing import Any, Dict, Mapping, Optional, Type, Union
from django import forms
from django.core.files.base import File
from django.db.models import F
from django.db.models.base import Model
from django.forms.utils import ErrorList
from .models import *


class BoxesForm(forms.ModelForm):
    clientfrom = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
    }))
    clientto = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
    }))
    phonefrom = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
    }))
    phoneto = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
    }))
    addressfrom = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
    }))
    addressto = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
    }))
    tarif = forms.FloatField(required=False, initial=0, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
    }))
    comment = forms.CharField(required=False, widget=forms.Textarea(attrs={
        'rows': 3,
        'class': 'form-control',
    }))
    amount = forms.FloatField(required=False, initial=0, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
    }))
    weight = forms.FloatField(required=False, initial=0, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
    }))
    volumesm = forms.FloatField(required=False, initial=0, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
    }))
    delivery = forms.FloatField(required=False, initial=0, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
    }))
    minsm = forms.FloatField(required=False, initial=0, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
    }))
    maxsm = forms.FloatField(required=False, initial=0, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
    }))
    discount = forms.FloatField(required=False, initial=0, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
    }))
    val = (
        ('TMT', 'Manat'),
        ('USD', 'Dollar')
    )
    valuta = forms.TypedChoiceField(
        choices=val, widget=forms.Select(attrs={'class': 'form-control', }))
    toleg = (
        ('', '----------'),
        ('tolendi', 'tolendi'),
        ('tolenmedi', 'tolenmedi'),
    )
    payment = forms.TypedChoiceField(
        choices=toleg, widget=forms.Select(attrs={'class': 'form-control', }))

    boximg = forms.FileField(required=False, widget=forms.FileInput(attrs={
        'class': 'form-control',
    }))
    regionfrom = forms.ModelChoiceField(queryset=Region.objects.all(
    ), widget=forms.Select(attrs={'class': 'form-control', }))
    regionto = forms.ModelChoiceField(required=False, queryset=Region.objects.all(
    ), widget=forms.Select(attrs={'class': 'form-control', }))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance:
            self.fields['payment'].initial = self.instance.payment
            self.fields['valuta'].initial = self.instance.valuta

    class Meta:
        model = Boxes
        fields = "__all__"


class RegionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(RegionForm, self).__init__(*args, **kwargs)
        self.fields['hi_region'] = forms.ModelChoiceField(
            queryset=Region.objects.filter(hi_region=F('name'))
        )
        self.fields['hi_region'].required = False
        self.fields['hi_region'].widget.attrs['class'] = 'form-control'
        self.fields['tarif'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['class'] = 'form-control'

    class Meta:
        model = Region
        fields = "__all__"


class CartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = "__all__"


class BoxHistoryForm(forms.ModelForm):
    class Meta:
        model = BoxHistory
        fields = "__all__"


class NotificationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(NotificationForm, self).__init__(*args, **kwargs)

        self.fields['theme'].widget.attrs['class'] = 'form-control'
        self.fields['maintxt'].widget.attrs['class'] = 'form-control'
        self.fields['image'].widget.attrs['class'] = 'form-control'

    class Meta:
        model = Notification
        fields = "__all__"


class FeedbackForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(FeedbackForm, self).__init__(*args, **kwargs)

        self.fields['comment'].widget.attrs['class'] = 'form-control'
        self.fields['comment'].widget.attrs['placeholder'] = 'Добавьте свое сообщение'
        self.fields['comment'].widget.attrs['style'] = 'width: max-content;'

        self.fields['answer'].widget.attrs['class'] = 'form-control'
        self.fields['answer'].widget.attrs['placeholder'] = 'Добавьте свой ответ'
        self.fields['answer'].widget.attrs['style'] = 'width: max-content'

        

    class Meta:
        model = Feedback
        fields = "__all__"


class PointForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PointForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Point
        fields = "__all__"

templates/boxes/form.html
{% extends 'base/base.html' %} {% block content %}

<div class="container">
  <br />
  <h2 class="h2">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      fill="currentColor"
      class="bi bi-box"
      viewBox="0 0 16 16"
    >
      <path
        d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5 8 5.961 14.154 3.5 8.186 1.113zM15 4.239l-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464L7.443.184z"
      />
    </svg>
    Создать коробку
  </h2>

  <form
    method="POST"
    enctype="multipart/form-data"
    class="card-body cardbody-color needs-validation"
    novalidate
  >
    {% csrf_token %}
    <div class="row g-5">
      <div class="col-md-8 col-lg-10">
        <form class="needs-validation" novalidate>
          <div class="row g-3">
            <div class="col-sm-6">
              <div class="panel" style="background: lightgreen; padding: 10px">
                <label for="id_clientfrom" class="form-label">Клиент отправитель</label
                ><br />
                {{ form.clientfrom }} <br />
                <label for="id_phonefrom" class="form-label">Телефон отправителья</label>
                <br />
                {{ form.phonefrom }}<br />
                <label for="id_addressfrom" class="form-label"
                  >Адрес отправителья</label
                >
                <br />
                {{ form.addressfrom }}<br />
                <label for="id_regionfrom" class="form-label"
                  >Регион отправителья</label
                >
                <br />
                {{ form.regionfrom }}<br />
              </div>
            </div>

            <div class="col-sm-6">
              <div class="panel" style="background: lightblue; padding: 10px">
                <label for="id_clientto" class="form-label">Клиент получатель</label
                ><br />
                {{ form.clientto }}<br />
                <label for="id_phoneto" class="form-label">Телефон получателья</label>
                <br />
                {{ form.phoneto }}<br />
                <label for="id_addressto" class="form-label">Адрес получателья</label>
                <br />
                {{ form.addressto }}<br />
                <label for="id_regionto" class="form-label">Регион получателья</label>
                <br />
                {{ form.regionto }}<br />
              </div>
            </div>
          </div>
          <br />
          <table>
            <tr>
              <td>
                <label for="id_tarif" class="form-label">Цена тарифа</label>
              </td>
              <td>
                <label for="id_amount" class="form-label">Цена коробки</label>
              </td>
              <td></td>
              <td>Платеж</td>
            </tr>
            <tr>
              <td>{{ form.tarif }}</td>
              <td>{{ form.amount }}</td>
              <td>{{ form.valuta }}</td>
              <td>{{ form.payment }}</td>
            </tr>
            <tr>
              <td>
                <label for="id_discount" class="form-label">Скидка</label>
              </td>
              <td><label for="id_weight" class="form-label">Вес</label></td>
              <td>
                <label for="id_boximg" class="form-label">Фото коробки</label>
              </td>
            </tr>
            <tr>
              <td>{{ form.discount }}</td>
              <td>{{ form.weight }}</td>
              <td>{{ form.boximg }}</td>
            </tr>
            <tr>
              <td>Комментарий</td>
            </tr>
            <tr>
              <td>{{ form.comment }}</td>
            </tr>
          </table>

          <div style="display: none">
            {{ form.status }} {{ form.user }} {{ form.placecount }}
          </div>

          <hr class="my-3" />

          <button class="w-40 btn btn-primary" type="submit">Подтверждать</button>
        </form>
      </div>
    </div>
  </form>
</div>

{% endblock content %}

templates/boxes/selected.html
{% extends 'base/base.html' %} {% block title %}Dashboard{% endblock title %}
{% block content %}

<div class="justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2">
    <h3 class="h3">Выделенные коробки</h3>
    <div class="row">
        <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
            {% csrf_token %}
            <!-- {{ form.userto }} -->
            <!-- {{ form.status }} -->
            <div class="col-6">
                <div class="d-flex align-items-center justify-content-evenly">
                    <div class="col-md-4 position-relative">
                        <select class="form-control" name="userto" id="id_userto" required>
                            <option value="" selected disabled>--Выбрать-пользователя---</option>
                            {% for cuser in cuserlist %}
                            <option value="{{ cuser.id }}">{{ cuser.name }} - {{ cuser.region }}</option>
                            {% endfor %}
                        </select>
                        <div class="invalid-tooltip">
                            Пожалуйста, выберите пользователя.
                        </div>
                        <div class="valid-tooltip" style="display: none;">
                            Выглядит неплохо!
                        </div>
                    </div>
                    <div class="col-md-4 position-relative">
                        <select class="form-control" name="status" id="id_status"
                            style="margin-left: 10px; margin-right: 10px" required>
                            <option value="" selected disabled>--Выбрать-статус---</option>
                            <option value="create">Create</option>
                            <option value="called">Called</option>
                            <option value="approved">Approved</option>
                            <option value="accepted">Accepted</option>
                            <option value="sent">Sent</option>
                            <option value="rejected">Rejected</option>
                            <option value="canceled">Canceled</option>
                            <option value="closed">Closed</option>
                        </select>
                        <div class="invalid-tooltip" style="margin-left: 10px;">
                            Пожалуйста, выберите статус.
                        </div>
                    </div>

                    <input class="btn btn-primary" type="submit" value="Ввод" />
                </div>
            </div>
        </form>
    </div>

</div>
<div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th colspan="2">Номер</th>
                <th>Клиент отправитель</th>
                <th>Телефон отправителья</th>
                <th>Регион отправителья</th>
                <th>Клиент получатель</th>
                <th>Регион получателья</th>
            </tr>
        </thead>
        <tbody>
            {% for box in cart %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="{% url 'boxselect' box.box.id %}">
                        <span data-feather="check-square" class="align-text-bottom"></span>
                    </a>
                </td>
                <td>{{ box.box.clientfrom }}</td>
                <td>{{ box.box.phonefrom }}</td>
                <td>{{ box.box.regionfrom }}</td>
                <td>{{ box.box.clientto }}</td>
                <td>{{ box.box.regionto }}</td>
            </tr>
            {% empty %}
            Вы не выбрали коробки
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}

templates/boxes/update.html
{% extends 'base/base.html' %} {% block content %}

<div class="container">
  <br />
  <h2 class="h2">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      fill="currentColor"
      class="bi bi-box"
      viewBox="0 0 16 16"
    >
      <path
        d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5 8 5.961 14.154 3.5 8.186 1.113zM15 4.239l-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464L7.443.184z"
      />
    </svg>
    Коробка
  </h2>

  <form method="POST" enctype="multipart/form-data" class="card-body cardbody-color needs-validation" novalidate>
    {% csrf_token %}
    <div class="row g-5">
      <div class="col-md-8 col-lg-10">
        {% comment %} <h4 class="mb-3">Billing address</h4> {% endcomment %}
        <form class="needs-validation" novalidate>
          <div class="row g-3">
            <div class="col-sm-6">
              <div class="panel" style="background: lightgreen; padding: 10px">
                <label for="id_clientfrom" class="form-label">Клиент отправитель</label
                ><br />
                {{ form.clientfrom }} <br />
                <label for="id_phonefrom" class="form-label">Телефон отправителья</label>
                <br />
                {{ form.phonefrom }}<br />
                <label for="id_addressfrom" class="form-label"
                  >Адрес отправителья</label
                >
                <br />
                {{ form.addressfrom }}<br />
                <label for="id_regionfrom" class="form-label"
                  >Регион отправителья</label
                >
                <br />
                {{ form.regionfrom }}<br />
              </div>
            </div>

            <div class="col-sm-6">
              <div class="panel" style="background: lightblue; padding: 10px">
                <label for="id_clientto" class="form-label">Клиент получатель</label
                ><br />
                {{ form.clientto }}<br />
                <label for="id_phoneto" class="form-label">Телефон получателья</label>
                <br />
                {{ form.phoneto }}<br />
                <label for="id_addressto" class="form-label">Адрес получателья</label>
                <br />
                {{ form.addressto }}<br />
                <label for="id_regionto" class="form-label">Регион получателья</label>
                <br />
                {{ form.regionto }}<br />
              </div>
            </div>
          </div>
          <br />
          <table>
            <tr>
              <td><label for="id_tarif" class="form-label">Цена тарифа</label> </td>
              <td><label for="id_amount" class="form-label">Цена коробки</label> </td>
              <td></td>
              <td>TПлатежoleg</td>
            </tr>
            <tr>
              <td>{{ form.tarif }}</td>
              <td>{{ form.amount }} </td>
              <td>{{ form.valuta }}</td>
              <td>{{ form.payment }}</td>
            </tr>
            <tr>
              <td><label for="id_discount" class="form-label">Скидка</label></td>
              <td><label for="id_weight" class="form-label">Вес</label></td>
              <td><label for="id_boximg" class="form-label">Фото коробки</label></td>
            </tr>
            <tr>
              <td>{{ form.discount }}</td>
              <td>{{ form.weight }}</td>
              <td>{{ form.boximg }}</td>
            </tr>
            <tr>
              <td>Комментарий</td>
            </tr>
            <tr>
              <td>{{ form.comment }}</td>
            </tr>
          </table>
           
          <div style="display: none">{{ form.status }} {{ form.user }} 
            {{ form.placecount }}</div>

          <hr class="my-3" />

          <button class="w-40 btn btn-primary" type="submit">Подтверждать</button>
        </form>
      </div>
    </div>
  </form>
</div>

{% endblock content %}